from fb_posts import scrape_comments_from_last_scrape, scrape_posts_from_last_scrape, scrape_posts_from_last_scrape_kafka, scrape_all_comments
scrape_posts_from_last_scrape("115285708497149")
scrape_posts_from_last_scrape_kafka("oronopaddlers")
scrape_all_comments("oronopaddlers")
